version: '3.8'
services:
  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecomdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    networks:
      - ecommerce-net

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: ecomdb
    ports:
      - "3306:3306"
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
